name: Push Proxies to Coding from Packagist

on:
  push: [ 'main' ]
  pull_request: [ 'main' ]
  workflow_dispatch:

env:
  CODING_URL: ${{ secrets.CODING_URL }}
  CODING_LOGIN: ${{ secrets.CODING_LOGIN }}
  CODING_PASSWORD: ${{ secrets.CODING_PASSWORD }}

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '7.0', '7.1', '7.2', '8.1' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - name: Pull Composer
        run: |
          cd src/zenboard
          composer update -oW --ignore-platform-reqs
          cd ../control
          composer update -oW --ignore-platform-reqs

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - name: Build Composer
        run: |
          composer install -o
          php main.php
