name: Push Proxies to CNB from Packagist

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CNB_URL: ${{ secrets.CNB_URL }}
  CNB_LOGIN: ${{ secrets.CNB_LOGIN }}
  CNB_PASSWORD: ${{ secrets.CNB_PASSWORD }}

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '7.0', '7.1', '7.2', '8.1' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - name: Pull Composer
        run: |
          cd src/zenboard
          composer update -oW --ignore-platform-reqs
          cd ../control
          composer update -oW --ignore-platform-reqs

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - name: Build Composer
        run: |
          composer install -o
          php main.php
